version: "3"

services:
  server:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
       - ./app/dist/:/usr/local/src/app/
       - ./containers/nginx/config/nginx.conf:/etc/nginx/nginx.conf
